### ISSUE TITLE
User can see their car.

### ISSUE THREAD

**Issue by ChristinaL24** [ChristinaL24/driving-game#1]
## 💰 Motivation

The user needs to see what they will be controlling.

## 📐 Plan

Put a top-down image of a car on the page.

## ✅ Task List

- [x] Create an index.html file, a styles.css file, and a layout.css file 
- [x] Create the html skeleton for the page
- [x] Link the both css files to the html file
- [x] Add the grass and car image to the html file
- [x] Style the page accordingly in respective layout and styles css files

**Comment by ChristinaL24** [comment]
Issue Template
Open a new Issue on your GitHub repository with the title User can see their car and paste the following block of [Markdown](https://guides.github.com/features/mastering-markdown/) into the comment box.

You will attempt to write your own task list before coding this feature. Refer to past projects for an example of what a task list should look like. Lots of small tasks is better than a few large tasks.

**Comment by ChristinaL24** [comment]
https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax
