### ISSUE TITLE
User can turn their car.

### ISSUE THREAD

**Issue by ChristinaL24** [ChristinaL24/driving-game#2]
## 💰 Motivation

The user needs to be able to control which way their car is facing.

## 📐 Plan

Rotate the image with CSS classes when the user presses an arrow key.

## ✅ Task List

- [x] Create a main.js file 
- [x] Link the html to the main.js
- [ ] Query the dom for car image
- [ ] Add an event listener for the keyboards

**Comment by ChristinaL24** [comment]
Hints!
Create a simple data model that includes which way the car is facing, (north, south, east, or west).
Listen for 'keydown' events on the document.

**Comment by ChristinaL24** [comment]
Issue Template
Open a new Issue on your GitHub repository with the title User can see their car and paste the following block of [Markdown](https://guides.github.com/features/mastering-markdown/) into the comment box.

You will attempt to write your own task list before coding this feature. Refer to past projects for an example of what a task list should look like. Lots of small tasks is better than a few large tasks.
